services:
  studyapi:
    container_name: study-api
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/ash -c "npm run start:dev"
    ports:
      - 8001:8001
    volumes:
      - .:/myapp
      - /myapp/node_modules
    networks:
      - study_network
    labels:
      - 'traefik.bar.frontend.rule=PathPrefix:/api/'
      - 'traefik.bar.port=8001'
    extra_hosts:
      - 'docker.localhost:host-gateway'

networks:
  study_network:
    external: true
