export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';

export const MONGOOSE_ID_CAST_ERROR = 'MONGOOSE_ID_CAST_ERROR';

export const INVALID_BODY = 'INVALID_BODY';

export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const CLASSROOM_NOT_FOUND = 'CLASSROOM_NOT_FOUND';

export const MUST_BE_A_TEACHER = 'MUST_BE_A_TEACHER';

export const USER_NOT_IN_CLASSROOM = 'USER_NOT_IN_CLASSROOM';

// MOGNOOSE SCHEMA ERRORS
export const USERNAME_MISSING = 'USERNAME_MISSING';
export const EMAIL_MISSING = 'EMAIL_MISSING';
export const FIRST_NAME_MISSING = 'FIRST_NAME_MISSING';
export const LAST_NAME_MISSING = 'LAST_NAME_MISSING';
export const PASSWORD_MISSING = 'PASSWORD_MISSING';
export const DATE_OF_BIRTH_MISSING = 'DATE_OF_BIRTH_MISSING';
export const NATIONALITY_MISSING = 'NATIONALITY_MISSING';

export const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';

export const ACCESS_TOKEN_HAS_EXPIRED = 'ACCESS_TOKEN_HAS_EXPIRED';
export const ACCESS_TOKEN_MISSING = 'ACCESS_TOKEN_MISSING';

export const REFRESH_TOKEN_HAS_EXPIRED = 'REFRESH_TOKEN_HAS_EXPIRED';
export const REFRESH_TOKEN_MISSING = 'REFRESH_TOKEN_MISSING';
